### ISSUE TITLE
Dual SIM issue

### ISSUE THREAD

**Issue by jonbarh** [aquaris-dev/android_device_bq_vegetalte#2]
Hi:
First of all I want to thank you for your work, I just installed 14.1-20180127-nightly and I'm very pleased with it. One feature that I'm missing from stock ROM that I hadn't been able to find is the posiblity of enable/disable the SIMs, there is no switch in SIM cards menu. Is this a bug o it must be a feature request? Is there a way to have two separate icons in quick settings tile (expanded) for each SIM card too?

Thanks in advance.
Regards

Aquaris E54G 1GB/16GB
Lineage-14.1-20180127-nightly-vegetalte
![photo_2018-02-02_16-34-39](https://user-images.githubusercontent.com/12173190/35741213-82f160e8-0837-11e8-8ec4-eec7ca41ac6b.jpg)

**Comment by Kra1o5** [comment]
Hi @jonbarh,
Correct, We dont have this feature implemented.
You can request it at: https://jira.lineageos.org
Regards,
